version: '3'
services:
  web:
    image: nginx
    volumes:
      - "./www:/usr/share/nginx/html:rw"
      - "./siteconf/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      - backend
    links:
      - php
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    volumes:
      - ./kalai:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
       MYSQL_ROOT_PASSWORD: kalai
       MYSQL_DATABASE: kalai_db
       MYSQL_USER: kalai_user
       MYSQL_PASSWORD: kalai_user_pass
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    networks:
      - frontend
      - backend
  php:
    image: php:7.4-fpm-alpine
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./www:/usr/share/nginx/html/
    restart: always
    networks:
      - frontend
    links:
      - web
volumes:
  kalai:
  www:
  siteconf:
networks:
  frontend:
  backend: